# Main prompt configuration
format = """
$pulumi$gcloud\
$all\
$line_break\
$character
"""

[pulumi]
symbol = "ğŸ“¡ "
format = '$symbol[$stack]($style) '

[gcloud]
symbol = 'â˜\(GCP\) '
format = '[$account(@$domain(/$project))(\($region\))]($style)'

# Configure the directory module to be concise
[directory]
truncation_symbol = "â€¦/"
truncate_to_repo = true
